spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/library
    username: librarian
    password: librarian
    hikari:
      minimumIdle: 1
      maximumPoolSize: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
#
#logging:
#  level:
#    root: DEBUG

